export const ADD_PRODUCEDMILK_REQUEST="ADD_MILK_REQUEST";
export const ADD_PRODUCEDMILK_SUCCESS="ADD_MILK_SUCCESS";
export const ADD_PRODUCEDMILK_FAILURE="ADD_MILK_FAILURE";

export const GET_PRODUCEDMILK_REQUEST="GET_MILK_REQUEST";
export const GET_PRODUCEDMILK_SUCCESS="GET_MILK_SUCCESS";
export const GET_PRODUCEDMILK_FAILURE="GET_MILK_FAILURE";