export const ADD_HEALTH_REQUEST="ADD_HEALTH_REQUEST";
export const ADD_HEALTH_SUCCESS="ADD_HEALTH_SUCCESS";
export const ADD_HEALTH_FAILURE="ADD_HEALTH_FAILURE";

export const GET_HEALTH_REQUEST="GET_HEALTH_REQUEST";
export const GET_HEALTH_SUCCESS="GET_HEALTH_SUCCESS";
export const GET_HEALTH_FAILURE="GET_HEALTH_FAILURE";