export const CUSTOMER_USER_REQUEST = "CUSTOMER_USER_REQUEST";
export const CUSTOMER_USER_SUCCESS = "CUSTOMER_USER_SUCCESS";
export const CUSTOMER_USER_FAILURE = "CUSTOMER_USER_FAILURE";


export const GET_CUSTOMER_REQUEST = "GET_CUSTOMER_REQUEST";
export const GET_CUSTOMER_SUCCESS = "GET_CUSTOMER_SUCCESS";
export const GET_CUSTOMER_FAILURE = "GET_CUSTOMER_FAILURE";

